// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4CxEyyQgKQOP2l_wQgyjivFCQkDKLbSI',
    appId: '1:6105728895:web:4cc3f46387b5b91bc5fc4a',
    messagingSenderId: '6105728895',
    projectId: 'devstart-8e5c0',
    authDomain: 'devstart-8e5c0.firebaseapp.com',
    storageBucket: 'devstart-8e5c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIpBNPZ6NiONLs3QGMfysKvRpywbSHbMI',
    appId: '1:6105728895:android:97e833ea000c0f79c5fc4a',
    messagingSenderId: '6105728895',
    projectId: 'devstart-8e5c0',
    storageBucket: 'devstart-8e5c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQZRL09C_0u4CeHph2llkNH6jZjMzN1n0',
    appId: '1:6105728895:ios:a86eb96f20ad072dc5fc4a',
    messagingSenderId: '6105728895',
    projectId: 'devstart-8e5c0',
    storageBucket: 'devstart-8e5c0.firebasestorage.app',
    iosClientId: '6105728895-uej6fgr9bv97ogpb96qmn00c31n8r3c6.apps.googleusercontent.com',
    iosBundleId: 'com.minghwidev.devstart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQZRL09C_0u4CeHph2llkNH6jZjMzN1n0',
    appId: '1:6105728895:ios:a86eb96f20ad072dc5fc4a',
    messagingSenderId: '6105728895',
    projectId: 'devstart-8e5c0',
    storageBucket: 'devstart-8e5c0.firebasestorage.app',
    iosClientId: '6105728895-uej6fgr9bv97ogpb96qmn00c31n8r3c6.apps.googleusercontent.com',
    iosBundleId: 'com.minghwidev.devstart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4CxEyyQgKQOP2l_wQgyjivFCQkDKLbSI',
    appId: '1:6105728895:web:1b8365bce06a5502c5fc4a',
    messagingSenderId: '6105728895',
    projectId: 'devstart-8e5c0',
    authDomain: 'devstart-8e5c0.firebaseapp.com',
    storageBucket: 'devstart-8e5c0.firebasestorage.app',
  );
}
